- set_fact:
    role_packages:
      - rsync

- set_fact:
    role_packages: "{{role_packages}} + ['rsync-daemon']"
  when: >
    ansible_os_family == "RedHat"

- include_role:
    name: data-utilities
    tasks_from: install_packages

- name: configure firewall for rsync
  firewalld:
    zone: "{{item}}"
    service: rsyncd
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - "{{rsyncd_firewall_zones}}"
  when: >
    (firewalld_available is defined and
    firewalld_available == True) and
    rsyncd_firewall_zones is defined

- name: copy rsyncd config
  template:
    src: rsyncd.conf.j2
    dest: /etc/rsyncd.conf
    mode: 0644
  when: rsyncd_shares is defined
  notify:
    - restart rsyncd

- name: enable rsyncd
  service: name=rsyncd enabled=yes state=started